# This is a basic workflow to help you get started with Actions
name: Run Dynatrace Webhook to workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "webhook"
  webhoook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - id: env-setup
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_URN: ${{ secrets.CLIENT_URN }}
        run: |
          echo bearer=$(curl --request POST \
          --url https://sso.dynatrace.com/sso/oauth2/token \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          -d 'grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&resource=${{ secrets.CLIENT_URN }}' \
          | jq -r .access_token)
      
      - run: echo ${{ steps.env-setup.outputs.bearer }}
        
      - name: Run Dynatrace Workflow webhook
        env:
          BEARER_TOKEN: ${{ steps.env-setup.outputs.bearer }}
        run: |
          curl --request POST \
          --url https://ffb97160.apps.dynatrace.com/platform/automation/v1/workflows/d0c1eba7-b4e6-4135-a1c3-b55fa1f44bcd/run \
          --header 'authorization: Bearer ${{ steps.env-setup.outputs.bearer }}' \
          --header 'content-type: application/json'
